### ISSUE TITLE
error uploading

### ISSUE THREAD

**Issue by skeeran** [rdeanar/yii2-file-processor#1]
when i upload i get this: error uploading

my config 

```
'fp' => [
            'class' => 'deanar\fileProcessor\Module',
            'space_replacement' => '-',
            'variations_config' => require(__DIR__ . '/file_processor_variations.php'),
            'upload_dir' => 'uploads',
            'default_quality' => 95,
            'default_resize_mod' => 'outbound',
            'unlink_files' => true,
        ],
```

**Comment by skeeran** [comment]
yii2-file-processor/vendor/FileAPI.php
correct in the 1 line from <? to <?php

and in file : yii2-file-processor/controllers/FileAPI.php
insert on 2 line namespace deanar\fileProcessor\controllers;

this solved the error for me... but the files are not getting uploaded

**Comment by rdeanar** [comment]
Make sure that your upload directory is writable. Is any records inserted in table fp_uploads?

The issue with FileAPI i will fix soon. At this moment i work on the major release.

**Comment by skeeran** [comment]
i have made it work allready... going through.. 

I like the way this module is working.. nice work... Waiting for future releases. Thanks

i changed also in Model 'Upload' from @app/web to @webroot

```
public function getUploadDir($type){
        return  Yii::getAlias('@webroot/'.$this->upload_dir.'/' . $type);
}
```

**Comment by rdeanar** [comment]
Thanks for improvement.
