### ISSUE TITLE
image not showing

### ISSUE THREAD

**Issue by skeeran** [rdeanar/yii2-file-processor#4]
hi, after update to new version, i am having this probleme.

Picture get uploaded and is showing also but when i referesh or comeback later to this page for uploading another picture the allready uploaded are not shown. I have checked the file exist.

i just dono where this part is done in your code... else i would check my self 

![image](https://cloud.githubusercontent.com/assets/7000138/6823938/461e1e40-d2ed-11e4-8b8b-03cd4d89d9f9.png)

**Comment by rdeanar** [comment]
Is any alerts or errors while uploading? (for more details about errors during upload, you can set up 'debug' => true in configuration, or see full response in Network inspector in browser).

How many files exists? Should be one file for each variation.

For displaying images in upload widget used method `getAlreadyUploadedByReference` from https://github.com/rdeanar/yii2-file-processor/blob/master/widgets/BaseUploadWidget.php#L75

**Comment by skeeran** [comment]
no error from debug, and also no error from firebug, no alert during upload
where is the path for the images configured?

**Comment by skeeran** [comment]
my files are stored in web/uploads/"type"/filename

**Comment by rdeanar** [comment]
That's right.  This is path by default.
You can configure it in module configuration by setting up custom root_path, upload_dir and root_url.

Here is example from README:
//'root_path' => '@frontend/web', // default: @webroot
//'root_url' => 'http://front.example.com', // default: current host (Yii::$app->request->getHostInfo())
'upload_dir' => 'uploads',

**Comment by skeeran** [comment]
for me this line solve the probleme : 

```
public function getAlreadyUploadedByReference($type, $type_id, $variation = '_thumb')
    {
...
 'src' => Yii::getAlias('@web').$item->getPublicFileUrl($variation),
....
```

the qustion is where this getPublicFileUrl() method comesfrom ?

**Comment by rdeanar** [comment]
How do you configured server?
The link to index page is localhost/**basic/web/**index.php or just localhost/index.php ?

You can configure `root_url`, set it up to `Yii::getAlias('@web')`.

**Comment by skeeran** [comment]
okay thank you: 
i have configured: root_url to @web

and please use in this files <?php insted <?    this is clean and avoid errors, there are server configuration where this cause error.

multi_upload_widget.php 
single_upload_widget.php
single_upload_widget_simple.php

**Comment by rdeanar** [comment]
Thank you for feedback.
