### ISSUE TITLE
Error while uploading ...

### ISSUE THREAD

**Issue by Zummer** [rdeanar/yii2-file-processor#5]
When I try to upload a photo, I get an error.
http://c2n.me/3iG8vWR - error screenshot
Set as described in the installation instructions. What am i doing wrong?

**Comment by Zummer** [comment]
Remote Address:127.0.0.1:80
Request URL:http://yii2-user/gallery/fp/base/upload?fileapi143327765840028
Request Method:POST
Status Code:404 Not Found
Response Headers
view source
Connection:Keep-Alive
Content-Length:33
Content-Type:text/html; charset=UTF-8
Date:Tue, 02 Jun 2015 20:43:15 GMT
Keep-Alive:timeout=10, max=100
Server:Apache/2.2.27 (Win32)
Request Headers
view source
Accept:_/_
Accept-Encoding:gzip, deflate
Accept-Language:ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Content-Length:531004
Content-Type:multipart/form-data; boundary=----WebKitFormBoundarym03g0hqjqAOfntbg
Cookie:_csrf=0653c9da111b546d8114d68ac2e22db2e644528fd793147eeb870ea3c0294597a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22klzmzdM0WkTmpJ-NeNoKI4-HBeu7NZRi%22%3B%7D; PHPSESSID=rphdqu107im2n3vtjkjn90nfi3
Host:yii2-user
Origin:http://yii2-user
Referer:http://yii2-user/gallery/album/update?id=7
User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36
X-Requested-With:XMLHttpRequest
Query String Parameters
view source
view URL encoded
fileapi143327765840028:

**Comment by rdeanar** [comment]
It's seems that request to wrong url. Response status is 404.

**Comment by Zummer** [comment]
Привет!
Да видел. Но в связи с чем 404?  Ведь я по инструкции всё сделал. Может настройки сервера? Я использую Open Server. 

Я также пробовал vova07/yii2-fileapi-widget - и загрузка здесь происходит нормально без ошибки. Но мне нужна мультизагрузка. У него она не реализована.

Я новичок, помоги разобраться. Почему не работает из коробки?

P/S В инструкции не указано где, в каком месте надо создать папку uploads.



-- 
С уважением,
Афанасьев Дмитрий
Icq: 480465310
Skype: the-afanasiev
Моб. тел.: +79529120451
ООО "Комфото", тел. +7(383)217-87-45, 217-87-41
Адрес: Россия, г. Новосибирск, ул. Вокзальная магистраль, 10
Эл. почта: afanasev@comefoto.ru


03.06.2015, 03:16, "Mikhail Razumovskiy" <notifications@github.com>:

**Comment by Zummer** [comment]
Да видел. Но в связи с чем 404?  Ведь я по инструкции всё сделал. Может настройки сервера? Я использую Open Server. 

Я также пробовал vova07/yii2-fileapi-widget - и загрузка здесь происходит нормально без ошибки. Но мне нужна мультизагрузка. У него она не реализована.

Я новичок, помоги разобраться. Почему не работает из коробки?

P/S В инструкции не указано где, в каком месте надо создать папку uploads.
