### ISSUE TITLE
Увеличивается размер оригинала фотографии в мегабайтах при загрузке на сервер

### ISSUE THREAD

**Issue by Zummer** [rdeanar/yii2-file-processor#6]
Увеличивается размер оригинала фотографии в мегабайтах при загрузке на сервер.
Разрешение в пикселях остается прежним (одинаковым с оригиналом). 
А размер в мегабайтах больше.
Загрузка с драйвером по умолчанию.

**Comment by rdeanar** [comment]
Нашел комментарий разработчики плагина fileapi

> ... если включен автоповорот, то в независимости от реального поворота, 
> изображение отправляется в канвас и уже он загружается на сервер. 
> Размер увеличивается именно по этой причине. 

Обновил версию, сделал опцию `imageAutoOrientation` по умолчанию выключенной, теперь приходит оригинал изображения. Чтобы опция стара возможной, необходимо обновиться.
